### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by cconstantine** [treeoftenere/Tenere#1]
I tried to follow the instructions in the readme, but I get this error when trying to run it:
```
No library found for com.thomasdiewald.pixelflow.java
No library found for com.thomasdiewald.pixelflow.java.fluid
Libraries must be installed in a folder named 'libraries' inside the 'sketchbook' folder
```

**Comment by mcslee** [comment]
Sorry about this - looks like a JAR file for a library was missing. I've just committed it.

**Comment by cconstantine** [comment]
No worries.  Thanks for the quick update.  It works for me now :)
