### ISSUE TITLE
Startup fails due to timeout in setup()

### ISSUE THREAD

**Issue by benkloester** [treeoftenere/Tenere#14]
When I try to run Tenere in Processing 3, I get the below error.

`java.lang.RuntimeException: Waited 5000ms for: <6d4a039b, 638de042>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-FPSAWTAnimator#00-Timer0-FPSAWTAnimator#00-Timer1>
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:410)
	at java.lang.Thread.run(Thread.java:748)`

It appears that this may be related to [this bug](https://github.com/processing/processing/issues/4468#issuecomment-227887007) in P3, where a call to framerate() early in the setup() thread is confounded by any blocking calls later in setup.

Commenting out line 54 of tenere.pde 
`frameRate(60.1);`
causes the project to launch without error.

**Comment by mcslee** [comment]
Hrm, weird. Are you on Mac or Windows? Curious why you have this issue and we didn't see it on our machines.

Can you try moving the frameRate call to the very end of the setup() function and seeing if that also fixes the issue? We can modify it as such if that helps.

**Comment by benkloester** [comment]
I'm on windows. Maybe whatever is timing out on my machine is completing in under 5s on yours? I'm not running on very flash hardware.

Moving the frameRate call to the end of setup() causes it to launch successfully. Thanks!

There are also a couple of unrelated errors but I'm not sure they deserve a ticket even. 

One is it seems that it is looking for a wav file that isn't in the repo.

`C:\Users\Ben\Documents\Ben\Projects\Code\Tenere-master\Tenere\media\ambient\Treescape - Mixed by Mark Slee.wav (The system cannot find the path specified)`

I guess I could download the mp3 [from here](https://api.soundcloud.com/tracks/342976955/download?client_id=a3e059563d7fd3372b49b37f00a00bcf) and transcode it (ugh), but if it's needed perhaps it could be committed?

I also get this error:
`No pattern class found for Tenere$PatternSlideshow: Tenere$PatternSlideshow`

Finally, and I'm new to LX, so this is probably a nothingburger, but even when launching successfully (either by commenting out the frameRate() or moving it to a tail call), I still get some exceptions on launch. Including for completeness. Everything seems to work now though.

`RunnableTask.run(): A caught exception occured on thread main-Display-.windows_nil-1-EDT-1: RunnableTask[enqueued true[executed false, flushed false], tTotal 0 ms, tExec 0 ms, tQueue 0 ms, attachment null, throwable java.lang.RuntimeException: Waited 5000ms for: <35f6638, 1f0e930f>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.windows_nil-1-EDT-1>]
java.lang.RuntimeException: Waited 5000ms for: <35f6638, 1f0e930f>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.windows_nil-1-EDT-1>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at jogamp.newt.WindowImpl$ResizableAction.run(WindowImpl.java:2118)
	at jogamp.newt.DisplayImpl.runOnEDTIfAvail(DisplayImpl.java:450)
	at jogamp.newt.WindowImpl.runOnEDTIfAvail(WindowImpl.java:2782)
	at jogamp.newt.WindowImpl.setResizable(WindowImpl.java:2154)
	at com.jogamp.newt.opengl.GLWindow.setResizable(GLWindow.java:370)
	at processing.opengl.PSurfaceJOGL$5.run(PSurfaceJOGL.java:452)
	at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:127)
	at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:375)
DefaultEDT.run(): Caught exception occured on thread main-Display-.windows_nil-1-EDT-1: RunnableTask[enqueued false[executed true, flushed false], tTotal 5016 ms, tExec 5016 ms, tQueue 0 ms, attachment null, throwable java.lang.RuntimeException: Waited 5000ms for: <35f6638, 1f0e930f>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.windows_nil-1-EDT-1>]
java.lang.RuntimeException: Waited 5000ms for: <35f6638, 1f0e930f>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.windows_nil-1-EDT-1>
	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
	at jogamp.newt.WindowImpl$ResizableAction.run(WindowImpl.java:2118)
	at jogamp.newt.DisplayImpl.runOnEDTIfAvail(DisplayImpl.java:450)
	at jogamp.newt.WindowImpl.runOnEDTIfAvail(WindowImpl.java:2782)
	at jogamp.newt.WindowImpl.setResizable(WindowImpl.java:2154)
	at com.jogamp.newt.opengl.GLWindow.setResizable(GLWindow.java:370)
	at processing.opengl.PSurfaceJOGL$5.run(PSurfaceJOGL.java:452)
	at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:127)
	at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:375)`

**Comment by mcslee** [comment]
Okay, fixed the basic issue here:
https://github.com/treeoftenere/Tenere/commit/567c0b0c73ddaf1dc8a10d91ae0f440627409df9

The WAV file is not a big deal, safe to ignore. The file is annoyingly big to include in a repo. If you want to playback music you can just load up any file using the audio control in the top left of the LX Studio window.

I have not seen this other issue before. It looks related to that same problem of the setup taking over 5000ms on your machine. TBH I don't know why it would be taking that long for you, you might try instrumenting the code if you're curious with some timer calls to figure out where all the time is being spent. But if it runs okay it's probably not a concern... seems like JOGL internals stuff.

**Comment by benkloester** [comment]
Cool, I figures the wav was just background sound, but I was still learning LX so wasn't sure if it was used as an input to animations somehow. I'll load my own sounds in any case.

If I get time I might try profiling it to see what's causing it to time out, but as you say, if it works *shrug*

**Comment by rm312** [comment]
Just for reference, I've been having similar issues on my mac - its an older machine but still rapid. Loads of intermittant timeouts

moving framerate to the end of setup makes the sketch start super quick!! CHEERS :)
